### ISSUE TITLE
[NO RELEASES]

### ISSUE THREAD

**Issue by anxkhn** [Welding-Torch/Binary-Search-Tree-Visualiser#1]
Hey, 
The releases hyperlink takes you to the repo of original author [@urvesh254](https://github.com/urvesh254/)
Link to original repo : [https://github.com/urvesh254/BST-Visualization](https://github.com/urvesh254/BST-Visualization)

**Comment by Welding-Torch** [comment]
Hey,
Somehow, I saw this just today. 
I've fixed the issue. 
Thanks for pointing it out!
❤️
